f=imread('img/Fig1005(a)(wirebond_mask).tif');
w=[2 -1 -1;-1 2 -1;-1 -1 2];
g=abs(imfilter(double(f),w));
imshow(g, []);
gtop=g(1:120,1:120);
gtop=pixeldup(gtop,4);
figure,imshow(gtop,[ ]);
gbot=g(end-119:end,end-119:end);
gbot=pixeldup(gbot,4);
figure,imshow(gbot,[ ]);
g=abs(g);
figure,imshow(g,[ ]);
T=max(g(:));
g=g>=T;
figure,imshow(g);